### ISSUE TITLE
Any Plan for Mitaka Release?

### ISSUE THREAD

**Issue by PeterDsouza** [HCLTech-SSW/openstack-automation-saltstack#2]
Any Plan for Mitaka Release?

**Comment by HCLTech-SSW** [comment]
Hi Peter, 

We are already working on the plan of Mitaka release installation automation. Planning to update in 2-3 weeks of time.

**Comment by PeterDsouza** [comment]
@HCLTech-SSW  :+1: This project looks great. I'm waiting for Mitaka support.

**Comment by HCLTech-SSW** [comment]
Hi Peter,

Thanks for taking the interest in our project.

We have uploaded the updated version to support the deployment of OpenStack Mitaka release.

Regards,
HCLTech-SSW Team.
