### ISSUE TITLE
 Successfull installation of OpenStack.

### ISSUE THREAD

**Issue by ShahImitiaz** [HCLTech-SSW/openstack-automation-saltstack#3]
@HCLTech-SSW 
I have created the lab of openstack using this project.  The installation of openstack has been done in less than 2 hrs.  Its great  !!. 

I want to contribute in this project.

**Comment by HCLTech-SSW** [comment]
Hi, 

We are working on to provide the support of OpenStack Mitaka Release, you can fork and start making the changes after your commits we would review and merge your changes into the repository.

Team,
HCLTech-SSW.

**Comment by HCLTech-SSW** [comment]
Provided the Support of OpenStack Mitaka
