### ISSUE TITLE
Mitaka Release

### ISSUE THREAD

**Issue by ShahImitiaz** [HCLTech-SSW/openstack-automation-saltstack#4]
@HCLTech-SSW OpenStack has removed the installation guide of Mitaka Release,  Is there any chance from your side to provide the support of same.

**Comment by HCLTech-SSW** [comment]
Hi Imitiaz,

Thanks for taking the interest in our project.

We have uploaded the updated version to support the deployment of OpenStack Mitaka release.

Regards,
HCLTech-SSW Team.
